/**
 * Renders a Paper to Markdown with $ / $$ math delimiters (Pandoc, Obsidian,
 * Jupyter, GitHub).
 */
import type { Block, Paper, RefEntry, Runs } from "../doc.js";
import { toLatex } from "../math.js";

function runs(rs: Runs, { emphAll = false } = {}): string {
  const body = rs
    .map((r) => {
      switch (r.k) {
        case "text": return r.s;
        case "emph": return `**${r.s}**`;
        case "math": return `$${toLatex(r.e)}$`;
        case "cite": return `[${r.ids.join(", ")}]`;
        case "eqref": return `(${r.no})`;
        case "resref": return `${r.kind} ${r.number}`;
      }
    })
    .join("");
  return emphAll ? `*${body}*` : body;
}

function renderDisplay(b: Extract<Block, { k: "display" }>, qed: boolean): string {
  const tag = b.no ? ` \\tag{${b.no}}` : "";
  const tail = qed ? " \\quad \\blacksquare" : "";
  return `$$\n${toLatex(b.e)}.${tag}${tail}\n$$`;
}

function blocks(bs: Block[], { inProof = false } = {}): string {
  return bs
    .map((b, i) => renderBlock(b, { inProof, last: i === bs.length - 1 }))
    .join("\n\n");
}

function proofBody(body: Block[], label: string): string {
  const inner = blocks(body, { inProof: true });
  const endsWithDisplay = body[body.length - 1]?.k === "display";
  return `*${label}.* ${inner}${endsWithDisplay ? "" : " ∎"}`;
}

function renderBlock(b: Block, opts: { inProof: boolean; last: boolean }): string {
  switch (b.k) {
    case "para":
      return runs(b.runs);
    case "display":
      return renderDisplay(b, opts.inProof && opts.last);
    case "result": {
      const italic = b.kind !== "Definition" && b.kind !== "Remark" && b.kind !== "Example";
      const name = b.name ? ` (${b.name})` : "";
      let s = `**${b.kind} ${b.number}${name}.** ${runs(b.statement, { emphAll: italic })}`;
      if (b.proof) s += `\n\n${proofBody(b.proof, "Proof")}`;
      return s;
    }
    case "proofOf":
      return proofBody(b.body, `Proof of ${b.kind} ${b.number}`);
  }
}

function reference(r: RefEntry, i: number): string {
  const head = `${r.authors}, *${r.title}*`;
  switch (r.type) {
    case "journal": {
      const issue = r.issue ? `, no. ${r.issue}` : "";
      const pages = r.pages ? `, ${r.pages[0]}–${r.pages[1]}` : "";
      return `${i + 1}. ${head}, ${r.venue} **${r.vol}**${issue} (${r.year})${pages}.`;
    }
    case "book":
      return `${i + 1}. ${head}, ${r.publisher}, ${r.city}, ${r.year}.`;
    case "thesis":
      return `${i + 1}. ${head}, Ph.D. thesis, ${r.school}, ${r.year}.`;
    case "preprint":
      return `${i + 1}. ${head}, preprint, arXiv:${r.arxiv}.`;
  }
}

export function renderMarkdown(paper: Paper): string {
  const authors = paper.authors.map((a) => `**${a.name}**`).join(" · ");

  const sections = paper.sections
    .map((s, i) => `## ${s.appendix ? `Appendix A. ${s.title}` : `${i + 1}. ${s.title}`}\n\n${blocks(s.blocks)}`)
    .join("\n\n");

  const addresses = paper.authors
    .map((a) => `*${a.affiliation}.* Email: \`${a.email}\``)
    .join("\n\n");

  return `# ${paper.title}

${authors}${paper.appendixBy ? `\n\n*with an appendix by ${paper.appendixBy}*` : ""}

*${paper.date}*

> **Abstract.** ${runs(paper.abstract)}
>
> **Keywords:** ${paper.keywords.join("; ")}. **MSC 2020:** ${paper.msc.join(", ")}.

${sections}

## Acknowledgments

${runs(paper.acknowledgments)}

## References

${paper.references.map(reference).join("\n")}

${addresses}

*Generated by [theorem-ipsum](https://github.com/MithrilBytes/theorem-ipsum), seed \`${String(paper.seed)}\`.*
`;
}

export const markdownFragments = { runs, blocks };
